plugins {
	id 'java'
}

group = 'com.github.whitemaks'
version = '1.0-SNAPSHOT'

subprojects {
	ext {
		base_http_api_version = "v1.0.0"
		base_db_version = "v1.0.0"

		lombok_version = "1.18.42"
		gson_version = "2.11.0"
		allure_version = "2.30.0"
		junit_version = "6.0.0"

		allure_plugin_version = "3.0.0"
	}
}

allprojects {
	repositories {
		mavenCentral()

		maven {
			url 'https://jitpack.io'
		}
	}
}