plugins {
	id 'java'
	id 'java-library'
}

group = 'com.github.whitemaks'
version = '1.0-SNAPSHOT'

dependencies {
	api "org.projectlombok:lombok:${lombok_version}"
	api "com.google.code.gson:gson:${gson_version}"
	api "io.qameta.allure:allure-junit-platform:${allure_version}"
	api "org.junit.jupiter:junit-jupiter-api:${junit_version}"
	api "org.junit.jupiter:junit-jupiter-engine:${junit_version}"
	api "org.junit.jupiter:junit-jupiter-params:${junit_version}"

	annotationProcessor "org.projectlombok:lombok:${lombok_version}"
}